import { ToastContainer } from "react-toastify";
import SessionProvider from "./SessionProvider";
import TranstackProvider from "./context/TranstackProvider";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full bg-gray-900">
			<body className="h-full">
				<TranstackProvider>
					<SessionProvider>{children}</SessionProvider>
				</TranstackProvider>
				<ToastContainer />
			</body>
		</html>
	);
}
